### ISSUE TITLE
Unable to receive data from S3 source to Redis Broker

### ISSUE THREAD

**Issue by jewel-mascarenhas** [triggermesh/triggermesh-core#116]
I'm currently validating a basic use case of capturing events in Redis for S3 File Upload Event using a Triggermesh managed Redis Broker (`redisbroker.yml`). I'm able to receive those events in the SQS queue that is created as part of the `s3source.yml`

However, when I interact with the Redis Server using redis-cli, I'm unable to see any data being stored.
Can anyone please suggest if I'm missing out on any configurations?

```
kubectl exec -ti myredis-rb-redis-xxx -- redis-cli       
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> scan 0
1) "0"
2) (empty array)
```

```
kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
awss3source-s3data-xxx   1/1     Running   0          27m
knative-operator-xxx      1/1     Running   0          33m
myredis-rb-broker-xxx     1/1     Running   0          29m
myredis-rb-redis-xxx     1/1     Running   0          29m
operator-webhook-xxx     1/1     Running   0          33m
```
```
# redisbroker.yml
apiVersion: eventing.triggermesh.io/v1alpha1
kind: RedisBroker
metadata:
  name: myredis
```

```
# s3source.yml
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSS3Source
metadata:
  name: s3data
spec:
  arn: arn:aws:s3:::mytmsrc

  eventTypes:
  - s3:ObjectCreated:*

  auth:
    credentials:
      accessKeyID:
        valueFromSecret:
          name: aws
          key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        valueFromSecret:
          name: aws
          key: AWS_SECRET_ACCESS_KEY

  sink:
    ref:
      apiVersion: eventing.triggermesh.io/v1alpha1
      kind: RedisBroker
      name: myredis
```

**Comment by odacremolbap** [comment]
@jewel-mascarenhas moved the issue to this repo, since it sounds like this might be some sort of kubernetes related issue.

Can you post here the status of all elements?

- RedisBroker
- CloudEventsTarget
- Sockeye

I just tried the [getting started guide](https://github.com/triggermesh/triggermesh-core/blob/main/docs/getting-started-redis.md) and it works for me.

Also, you can simplify the scenario by skipping the `CloudEventsTarget` and connect the `RedisBroker` to Sockeye using a Trigger.

```yaml
apiVersion: eventing.triggermesh.io/v1alpha1
kind: Trigger
metadata:
  name: trigger-sockeye
spec:
  broker:
    kind: RedisBroker
    group: eventing.triggermesh.io
    name: myredis
  target:
    ref:
       apiVersion: serving.knative.dev/v1
       kind: Service
       name: sock
```
