### ISSUE TITLE
Filter: any with only one element not working

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/triggermesh-core#118]
Due to the recursive definition of filters it is hard to know which ones work.
This one is included in our fitlers samples but it does not seem to work.

```yaml
filters:
- any:
  - exact:
    type: demo.type11
```
